### ISSUE TITLE
文件过大渲染进度问题

### ISSUE THREAD

**Issue by javen1** [seapeak233/AndroidDocViewer#1]
当文件过大时，渲染会比较耗时，请问可以通过何种当时获取文件的渲染进度

**Comment by seapeak233** [comment]
我看了下PDFJS的源码，好像可以通过在这个文件下
https://github.com/seapeak233/AndroidDocViewer/blob/main/docviewer/src/main/assets/pdf/js/pdf.worker.mjs
line: 1652 这个方法 onReceiveProgressiveData 里注入JS事件，让WebView注册JS事件，来获取当前进度
希望能解决你的问题
